### ISSUE TITLE
tesla_powerwall not defined?

### ISSUE THREAD

**Issue by danman222** [Panda88CO/udi-TeslaPW2#11]
I get errors when udiTeslaPW2 starting (it never connects). Looks like an error in TeslaInfoV2.py @ line 13:

 `from tesla_powerwall import GridStatus, OperationMode, MeterType`

I don't see tesla_powerwall defined anywhere

Ref:
https://github.com/Panda88CO/udi-TeslaPW2/blob/5a2b426c4eb0d285b874b18c0f75efe90c84a3cb/TeslaInfoV2.py#L13

Log:
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaPW2main.py", line 6, in <module>
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from TeslaInfoV2 import tesla_info
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaInfoV2.py", line 13, in <module>
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from tesla_powerwall import GridStatus, OperationMode, MeterType
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: ModuleNotFoundError
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: :
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: No module named 'tesla_powerwall'

**Comment by Panda88CO** [comment]
Looks like the library is requirements are notimportedChristian OlgaardSent and "auto corrected" by my iPhoneOn Dec 30, 2024, at 20:41, danman222 ***@***.***> wrote:﻿
I get errors when udiTeslaPW2 starting (it never connects). Looks like an error in TeslaInfoV2.py @ line 13:
from tesla_powerwall import GridStatus, OperationMode, MeterType
I don't see tesla_powerwall defined anywhere
Ref:
https://github.com/Panda88CO/udi-TeslaPW2/blob/5a2b426c4eb0d285b874b18c0f75efe90c84a3cb/TeslaInfoV2.py#L13
Log:
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaPW2main.py", line 6, in 
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from TeslaInfoV2 import tesla_info
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaInfoV2.py", line 13, in 
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from tesla_powerwall import GridStatus, OperationMode, MeterType
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: ModuleNotFoundError
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: :
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: No module named 'tesla_powerwall'

**Comment by Panda88CO** [comment]
Can you send log all log fileChristian OlgaardSent and "auto corrected" by my iPhoneOn Dec 30, 2024, at 20:41, danman222 ***@***.***> wrote:﻿
I get errors when udiTeslaPW2 starting (it never connects). Looks like an error in TeslaInfoV2.py @ line 13:
from tesla_powerwall import GridStatus, OperationMode, MeterType
I don't see tesla_powerwall defined anywhere
Ref:
https://github.com/Panda88CO/udi-TeslaPW2/blob/5a2b426c4eb0d285b874b18c0f75efe90c84a3cb/TeslaInfoV2.py#L13
Log:
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaPW2main.py", line 6, in 
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from TeslaInfoV2 import tesla_info
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaInfoV2.py", line 13, in 
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from tesla_powerwall import GridStatus, OperationMode, MeterType
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: ModuleNotFoundError
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: :
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: No module named 'tesla_powerwall'

**Comment by Panda88CO** [comment]
CorrectThe library seems not  to have been installed.  Look in requirements.txt.  You need to pip install thoseChristian OlgaardSent and "auto corrected" by my iPhoneOn Dec 30, 2024, at 20:41, danman222 ***@***.***> wrote:﻿
I get errors when udiTeslaPW2 starting (it never connects). Looks like an error in TeslaInfoV2.py @ line 13:
from tesla_powerwall import GridStatus, OperationMode, MeterType
I don't see tesla_powerwall defined anywhere
Ref:
https://github.com/Panda88CO/udi-TeslaPW2/blob/5a2b426c4eb0d285b874b18c0f75efe90c84a3cb/TeslaInfoV2.py#L13
Log:
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaPW2main.py", line 6, in 
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from TeslaInfoV2 import tesla_info
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ce5_16/TeslaInfoV2.py", line 13, in 
2024-12-30 13:35:32.060 MainThread udi_interface      ERROR    udi_interface:write: from tesla_powerwall import GridStatus, OperationMode, MeterType
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: ModuleNotFoundError
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: :
2024-12-30 13:35:32.061 MainThread udi_interface      ERROR    udi_interface:write: No module named 'tesla_powerwall'

**Comment by danman222** [comment]
Log file attached. Do I need to install something else?

[udiTeslaPW2_12-30-2024_31526_PM.zip](https://github.com/user-attachments/files/18277620/udiTeslaPW2_12-30-2024_31526_PM.zip)

**Comment by Panda88CO** [comment]
I  need the full log - it includes the install log where i may be able to see why the local library was not installed

________________________________

**Comment by danman222** [comment]
Attached
[pg3_12-30-2024_35228_PM.zip](https://github.com/user-attachments/files/18277717/pg3_12-30-2024_35228_PM.zip)
[system_12-30-2024_35250_PM.zip](https://github.com/user-attachments/files/18277718/system_12-30-2024_35250_PM.zip)

**Comment by danman222** [comment]
I am not a python coder but I notice this from requirements.txt:

   tesla-powerwall==0.3.19

Should that be tesla_powerwall==0.3.19  ??? (underscore vs. dash)

Also, current version of tesla_powerwall appears to be 0.5.2. Newer versions not tested?

Thanks, 
Dan

**Comment by Panda88CO** [comment]
Newer versions moved to async library and it will take a lot of effort to change all codeYou can see what happens if you download the full log and in the zip there is an install.logIt has been working for a while so i doubt there is a typoChristian OlgaardSent and "auto corrected" by my iPhoneOn Dec 31, 2024, at 02:35, danman222 ***@***.***> wrote:﻿
I am not a python coder but I notice this from requirements.txt:
tesla-powerwall==0.3.19
Should that be tesla_powerwall==0.3.19  ??? (underscore vs. dash)
Also, current version of tesla_powerwall appears to be 0.5.2. Newer versions not tested?
Thanks,
Dan

**Comment by Panda88CO** [comment]
Btw i am travelling so i have no access to my setupChristian OlgaardSent and "auto corrected" by my iPhoneOn Dec 31, 2024, at 02:35, danman222 ***@***.***> wrote:﻿
I am not a python coder but I notice this from requirements.txt:
tesla-powerwall==0.3.19
Should that be tesla_powerwall==0.3.19  ??? (underscore vs. dash)
Also, current version of tesla_powerwall appears to be 0.5.2. Newer versions not tested?
Thanks,
Dan

**Comment by Panda88CO** [comment]
I need you to go to log and Download Log Package
Sorry for not being clear

________________________________

**Comment by danman222** [comment]
I found it. Problem is this:
  ERROR: No matching distribution found for udi_interface>=3.3.15
[udiTeslaPW2_12-31-2024_101428_AM.zip](https://github.com/user-attachments/files/18282335/udiTeslaPW2_12-31-2024_101428_AM.zip)

**Comment by danman222** [comment]
Looks like it stopped installing everything after that in "requirements.txt"

**Comment by Panda88CO** [comment]
It.should be released.  I think you need to open ticket at udi for this one

**Comment by Panda88CO** [comment]
You need to find it under log

**Comment by danman222** [comment]
I didn't see anywhere in the PG3 UI to submit a support ticket but I submitted one from the UDI web

**Comment by danman222** [comment]
Quick response from UDI:

Benoit Mercier wrote:
Hi Daniel,
There is no udi_interface 3.3.15. The last release is 3.3.14.
I told Christian he should update the plugin accordingly.

**Comment by Panda88CO** [comment]
That is the way to do itChristian OlgaardSent and "auto corrected" by my iPhoneOn Dec 31, 2024, at 18:22, danman222 ***@***.***> wrote:﻿
I didn't see anywhere in the PG3 UI to submit a support ticket but I submitted one from the UDI web

**Comment by Panda88CO** [comment]
Ok. I'll try to fix itChristian OlgaardSent and "auto corrected" by my iPhoneOn Dec 31, 2024, at 18:41, danman222 ***@***.***> wrote:﻿
Quick response from UDI:
Benoit Mercier wrote:
Hi Daniel,
There is no udi_interface 3.3.15. The last release is 3.3.14.
I told Christian he should update the plugin accordingly.

**Comment by danman222** [comment]
After the holiday. Happy New Year!

**Comment by Panda88CO** [comment]
Did it already but it will take some time to depoly - you can also edit the requirement.txt to 3.3.14 and try to run install.sh

________________________________

**Comment by danman222** [comment]
I would but I'm a noob with all of this. I don't no how to console into the eisy.

**Comment by Panda88CO** [comment]
Ok - then delete and reinstall in the new slot - there are still some issues with upgrades in the node store - I assume you never to got it working

Happy New Year
Christian

________________________________

**Comment by danman222** [comment]
I just did a re-install in the same slot and ... looks like it's working now!
thanks,
Dan

**Comment by Panda88CO** [comment]
😁Christian OlgaardSent and "auto corrected" by my iPhoneOn Dec 31, 2024, at 19:09, danman222 ***@***.***> wrote:﻿
I just did a re-install in the same slot and ... looks like it's working now!
thanks,
Dan
